/* Fluxo simples: simulador ampliado, débitos importados como fonte principal e lançamentos manuais temporários. */
import { useEffect, useMemo, useState } from "react";
import * as XLSX from "xlsx";
import { toast } from "sonner";
import { AlertTriangle, CalendarDays, CheckCircle2, Download, FileSpreadsheet, Info, Menu, Plus, Upload, WalletCards, X } from "lucide-react";

type Entry = { id: string; date: string; debit: number; source: "imported" | "manual"; createdAt?: number };
type Grouped = { date: string; debit: number; limit: number; exceeded: boolean; critical?: string };
const STORAGE = "fluxo-caixa-debitos-v4";
const RESET_MARKER = "fluxo-caixa-base-limpa-v1";
const DAY = 86400000;
const money = (v: number) => v.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const dateBR = (v: string) => new Date(`${v}T12:00:00`).toLocaleDateString("pt-BR");
const iso = (d: Date) => d.toISOString().slice(0, 10);
const limitForDate = (date: string) => [5, 10, 15, 20, 25].includes(new Date(`${date}T12:00:00`).getDate()) ? 50000 : 75000;
const criticalLabel = (date: string) => ({ 5: "Folha de pagamento", 10: "Custos altos", 15: "Impostos", 20: "Adiantamento + impostos", 25: "Impostos" } as Record<number, string>)[new Date(`${date}T12:00:00`).getDate()];
function loadEntries(): Entry[] { try { if (!localStorage.getItem(RESET_MARKER)) { localStorage.removeItem("fluxo-caixa-debitos-v3"); localStorage.removeItem("fluxo-caixa-debitos-v4"); localStorage.setItem(RESET_MARKER, "1"); } const saved = JSON.parse(localStorage.getItem(STORAGE) || "null"); return Array.isArray(saved) ? saved.map((e: any) => ({ ...e, source: e.source || "imported" })) : []; } catch { return []; } }
const parseTerms = (value: string) => value.split(/[\s,;]+/).map((v) => Number(v)).filter((v) => Number.isFinite(v) && v > 0).slice(0, 12);
const parseBRL = (value: string) => { const normalized = value.replace(/\s/g, "").replace(/R\$?/gi, "").replace(/\./g, "").replace(",", "."); const parsed = Number(normalized); return Number.isFinite(parsed) ? parsed : 0; };

export default function Home() {
  const [tab, setTab] = useState<"fluxo" | "importar">("fluxo");
  const [entries, setEntries] = useState<Entry[]>(loadEntries);
  const [today, setToday] = useState(iso(new Date()));
  const [purchaseInput, setPurchaseInput] = useState("48.000,00");
  const [termsInput, setTermsInput] = useState("30, 60, 90");
  const [simulated, setSimulated] = useState(false);
  const [showAdd, setShowAdd] = useState(false);
  const [newEntry, setNewEntry] = useState({ date: iso(new Date()), debit: "" });
  const [importSummary, setImportSummary] = useState<{ count: number; start: string; end: string; total: number } | null>(null);
  const [mobileMenu, setMobileMenu] = useState(false);
  const [now, setNow] = useState(Date.now());
  const terms = parseTerms(termsInput);
  useEffect(() => localStorage.setItem(STORAGE, JSON.stringify(entries)), [entries]);
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 60000); return () => window.clearInterval(timer); }, []);
  const activeEntries = useMemo(() => entries.filter((e) => e.source === "imported" || !e.createdAt || now - e.createdAt < 7 * DAY), [entries, now]);
  const grouped = useMemo(() => { const groups = new Map<string, number>(); activeEntries.forEach((e) => groups.set(e.date, (groups.get(e.date) || 0) + Number(e.debit || 0))); return Array.from(groups.entries()).sort(([a], [b]) => a.localeCompare(b)).map(([date, debit]) => ({ date, debit, limit: limitForDate(date), exceeded: debit > limitForDate(date), critical: criticalLabel(date) })); }, [activeEntries]);
  const total = grouped.reduce((s, d) => s + d.debit, 0);
  const dueToday = grouped.find((d) => d.date === today);
  const criticalRows = grouped.filter((d) => d.critical);
  const purchase = parseBRL(purchaseInput);
  const dueDates = useMemo(() => { const parsed = terms.length ? terms : [30]; const installment = purchase / parsed.length; return parsed.map((term) => { const d = new Date(`${today}T12:00:00`); d.setDate(d.getDate() + term); const date = iso(d); const existing = grouped.find((row) => row.date === date)?.debit || 0; const limit = limitForDate(date); const canBuy = existing + installment <= limit; return { term, date, existing, installment, limit, canBuy }; }); }, [terms, purchase, purchaseInput, today, grouped]);
  const addDebit = () => { const value = Number(newEntry.debit.replace(",", ".")); if (!newEntry.date || !value || value <= 0) return toast.error("Informe uma data e um débito válido."); setEntries((all) => [...all, { id: crypto.randomUUID(), date: newEntry.date, debit: value, source: "manual", createdAt: Date.now() }]); setNewEntry({ date: today, debit: "" }); setShowAdd(false); toast.success("Dia e valor adicionados. Este registro será temporário por 7 dias."); };
  const removeDay = (date: string) => { if (confirm("Excluir todos os débitos deste dia?")) { setEntries((all) => all.filter((e) => e.date !== date)); toast.success("Débitos do dia excluídos."); } };
  const downloadTemplate = () => { const sheet = XLSX.utils.aoa_to_sheet([["Data de Operação", "Crédito", "Débito", "Saldo"], [today, 0, 0, 0]]); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, sheet, "Fluxo de Caixa"); XLSX.writeFile(wb, "modelo-fluxo-de-caixa.xlsx"); };
  const importFile = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const wb = XLSX.read(reader.result, { type: "array", cellDates: true }); const ws = wb.Sheets[wb.SheetNames[0]]; const rows = XLSX.utils.sheet_to_json<any[]>(ws, { header: 1, raw: true, defval: "" }); const headers = (rows[0] || []).map((h: any) => String(h).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")); const dateIndex = Math.max(0, headers.findIndex((h) => h.includes("data"))); const debitIndex = headers.findIndex((h) => h.includes("debito")); if (debitIndex < 0) throw new Error("Coluna Débito não encontrada"); const parseDate = (v: any) => v instanceof Date ? iso(v) : /^\d{4}-\d{2}-\d{2}$/.test(String(v)) ? String(v) : ""; const imported = rows.slice(1).map((r) => ({ id: crypto.randomUUID(), date: parseDate(r[dateIndex]), debit: typeof r[debitIndex] === "number" ? r[debitIndex] : parseBRL(String(r[debitIndex] || "")), source: "imported" as const })).filter((e) => e.date && e.debit > 0); if (!imported.length) throw new Error("Nenhum débito válido encontrado"); setEntries((all) => [...all.filter((e) => e.source === "manual" && e.createdAt && Date.now() - e.createdAt < 7 * DAY), ...imported]); const dates = imported.map((e) => e.date).sort(); setImportSummary({ count: imported.length, start: dates[0], end: dates[dates.length - 1], total: imported.reduce((s, e) => s + e.debit, 0) }); toast.success(`${imported.length} lançamentos importados. A planilha passa a ser a fonte principal do fluxo.`); } catch { toast.error("Não foi possível processar a planilha. Confira a coluna Débito."); } }; reader.readAsArrayBuffer(file); };
  return (
    <div className="simple-app">
      <header className="simple-header"><div className="brand"><div className="brand-mark">FC</div><div><strong>Fluxo de Caixa</strong><span>Contas a pagar</span></div></div><button className="mobile-menu" onClick={() => setMobileMenu(!mobileMenu)}><Menu size={20}/></button><nav className={mobileMenu ? "open" : ""}><button className={tab === "fluxo" ? "active" : ""} onClick={() => { setTab("fluxo"); setMobileMenu(false); }}>Fluxo de Caixa</button><button className={tab === "importar" ? "active" : ""} onClick={() => { setTab("importar"); setMobileMenu(false); }}>Importar Planilha</button></nav></header>
      <main className="simple-main">{tab === "fluxo" ? <>
        <div className="page-heading page-heading-compact"><div><p className="eyebrow">Contas a pagar</p><h1>Fluxo de Caixa</h1><p className="subheading">Simule compras futuras com os débitos importados.</p></div></div>
        <div className={simulated ? "sim-layout has-simulation" : "sim-layout"}>
          <aside className="card simulator simulator-large"><div className="card-heading"><div><h2>Simulador de compra</h2><p>Digite vários prazos separados por vírgula. O valor total será dividido entre eles.</p></div><span className="sim-badge">SIMULAR</span></div><div className="form-stack"><label>Data de hoje<input type="date" value={today} onChange={(e) => setToday(e.target.value)}/></label><label>Valor total da compra<input type="text" inputMode="decimal" value={purchaseInput} onChange={(e) => setPurchaseInput(e.target.value)} onBlur={() => { const value = parseBRL(purchaseInput); setPurchaseInput(value ? value.toLocaleString("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : ""); }} placeholder="40.000,00"/></label><label>Prazo da compra em dias<input type="text" value={termsInput} onChange={(e) => setTermsInput(e.target.value)} placeholder="30, 60, 90"/><small className="field-hint">Exemplo: 30, 60, 90 divide o valor em 3 parcelas.</small></label></div><button className="btn btn-primary full" onClick={() => { setSimulated(true); toast.success("Cenários de compra simulados."); }}>Simular compra</button></aside>
          {simulated && <section className="card simulation-panel"><div className="card-heading"><div><h2>Simulação da compra</h2><p>Confira cada prazo, impacto e limite disponível.</p></div></div><div className="scenario-list">{dueDates.map((scenario) => <div className={"scenario " + (scenario.canBuy ? "scenario-ok" : "scenario-risk")} key={scenario.term}><div className="scenario-title"><strong>{scenario.canBuy ? "PODE COMPRAR" : "NÃO PODE COMPRAR"}</strong><span>{scenario.term} dias</span></div><div className="scenario-grid"><div><span>Data prevista</span><strong>{dateBR(scenario.date)}</strong></div><div><span>Prazo</span><strong>Hoje + {scenario.term} dias</strong></div><div><span>Valor já existente</span><strong>{money(scenario.existing)}</strong></div><div><span>Valor da compra</span><strong>{money(scenario.installment)}</strong></div><div><span>Limite do dia</span><strong>{money(scenario.limit)}</strong></div></div><p>{scenario.canBuy ? "Débitos existentes + parcela ficam dentro do limite." : "Débitos existentes + parcela ultrapassam o limite."}</p></div>)}</div></section>}
        </div>
        <section className="card critical-card critical-below"><div className="card-heading"><div><h2>Datas críticas</h2><p>Os dias de maior atenção no fluxo.</p></div><AlertTriangle size={20}/></div><div className="critical-list">{criticalRows.map((d) => <div className={"critical-item " + (d.exceeded ? "critical-risk" : "")} key={d.date}><div><strong>Dia {new Date(d.date + "T12:00:00").getDate()}</strong><span>{d.critical}</span></div><div><b>{money(d.debit)}</b><small>de {money(d.limit)}</small></div></div>)}{!criticalRows.length && <div className="empty">Nenhuma data crítica carregada.</div>}</div></section>
        <section className="card timeline-card"><div className="card-heading"><div><h2>Débitos por dia</h2><p>Todos os débitos importados, organizados por data.</p></div><WalletCards size={20}/></div><div className="timeline-list">{grouped.map((d) => <div className="timeline-row" key={d.date}><div className="timeline-label"><strong>{dateBR(d.date)}</strong><span>{d.critical || "Demais pagamentos"}</span></div><div className="timeline-track"><div className={"timeline-fill " + (d.exceeded ? "fill-risk" : "")} style={{ width: String(Math.min(100, d.debit / d.limit * 100)) + "%" }}/></div><div className="timeline-value"><strong>{money(d.debit)}</strong><span>{money(Math.max(0, d.limit - d.debit))} livres</span></div><button className="icon-btn" onClick={() => removeDay(d.date)} title="Excluir dia"><X size={14}/></button></div>)}{!grouped.length && <div className="empty">Nenhum débito importado. Acesse “Importar Planilha” para começar.</div>}</div></section>
      </> : <ImportTab onFile={importFile} onDownload={downloadTemplate} summary={importSummary}/>}</main>
      {showAdd && <div className="modal-backdrop"><div className="modal-light"><div className="modal-title"><div><p className="eyebrow">Registro temporário</p><h2>Adicionar dia e valor compra</h2></div><button className="icon-btn" onClick={() => setShowAdd(false)}><X size={18}/></button></div><p className="modal-description">Este valor ajuda os compradores durante os próximos 7 dias e depois deixa de afetar o fluxo. A planilha importada continua sendo a fonte principal.</p><div className="form-stack"><label>Data de vencimento<input type="date" value={newEntry.date} onChange={(e) => setNewEntry({ ...newEntry, date: e.target.value })}/></label><label>Valor do débito<input type="number" min="0" value={newEntry.debit} onChange={(e) => setNewEntry({ ...newEntry, debit: e.target.value })}/></label></div><div className="modal-actions"><button className="btn btn-light" onClick={() => setShowAdd(false)}>Cancelar</button><button className="btn btn-dark" onClick={addDebit}>Salvar registro por 7 dias</button></div></div></div>}
    </div>
  );
}
function ImportTab({ onFile, onDownload, summary }: { onFile: (file?: File) => void; onDownload: () => void; summary: { count: number; start: string; end: string; total: number } | null }) { return <section className="import-page" aria-label="Importar planilha de débitos"><div className="page-heading"><div><p className="eyebrow">Atualização diária</p><h1>Importar Planilha</h1><p className="subheading">Envie o arquivo de contas a pagar. O sistema usa somente Data de Operação e Débito.</p></div></div><div className="import-grid"><label className="dropzone"><input type="file" accept=".xlsx,.csv" onChange={(e) => onFile(e.target.files?.[0])}/><Upload size={30}/><strong>Selecionar arquivo Excel</strong><span>.xlsx ou .csv</span></label><div className="card import-help"><FileSpreadsheet size={24}/><h2>Modelo correto</h2><p>O arquivo deve conter exatamente estas quatro colunas:</p><div className="columns"><span>1. Data de Operação</span><span>2. Crédito</span><span>3. Débito</span><span>4. Saldo</span></div><p className="muted">Durante o processamento, Crédito e Saldo são ignorados. Apenas Débito monta o fluxo.</p><button className="btn btn-dark full" onClick={onDownload}><Download size={16}/> Baixar modelo .xlsx</button></div></div>{summary && <div className="import-summary"><CheckCircle2 size={22}/><div><strong>Importação concluída</strong><span>{summary.count} lançamentos lidos · período de {dateBR(summary.start)} a {dateBR(summary.end)} · total de débitos: {money(summary.total)}</span></div></div>}</section>; }
