/* Fluxo simples: simulador ampliado, débitos importados como fonte principal e lançamentos manuais temporários. */
import { useEffect, useMemo, useRef, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { isTemporaryEntryActive } from "@shared/flowRules";
import { parsePaymentDates, calculateDaysFromReference, canPurchaseOnDate, getPurchaseLimitForDate } from "@shared/simulationRules";
import { GoalsTab, PurchasesDashboardTab } from "@/pages/PurchaseGoals";
import * as XLSX from "xlsx";
import { toast } from "sonner";
import { AlertTriangle, CalendarDays, CheckCircle2, Download, FileSpreadsheet, Info, Menu, Plus, Upload, WalletCards, X } from "lucide-react";

type Entry = { id: string; date: string; debit: number; source: "imported" | "manual"; createdAt?: number };
type Grouped = { date: string; debit: number; limit: number; exceeded: boolean; critical?: string; weekday: string; isCritical: boolean };
const STORAGE = "fluxo-caixa-debitos-v4";
const RESET_MARKER = "fluxo-caixa-base-limpa-v1";
const DAY = 86400000;
const money = (v: number) => v.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const dateBR = (v: string) => new Date(`${v}T12:00:00`).toLocaleDateString("pt-BR");
const dayMonthBR = (v: string) => new Date(`${v}T12:00:00`).toLocaleDateString("pt-BR", { day: "2-digit", month: "2-digit" });
const iso = (d: Date) => d.toISOString().slice(0, 10);
const limitForDate = (date: string) => getPurchaseLimitForDate(date).limit;
const criticalLabel = (date: string) => ({ 5: "Folha de pagamento", 10: "Custos altos", 15: "Impostos", 20: "Adiantamento + impostos", 25: "Impostos" } as Record<number, string>)[new Date(`${date}T12:00:00`).getDate()];
function loadEntries(): Entry[] { try { if (!localStorage.getItem(RESET_MARKER)) { localStorage.removeItem("fluxo-caixa-debitos-v3"); localStorage.removeItem("fluxo-caixa-debitos-v4"); localStorage.setItem(RESET_MARKER, "1"); } const saved = JSON.parse(localStorage.getItem(STORAGE) || "null"); return Array.isArray(saved) ? saved.map((e: any) => ({ ...e, source: e.source || "imported" })) : []; } catch { return []; } }
const parseTerms = (value: string) => value.split(/[\s,;]+/).map((v) => Number(v)).filter((v) => Number.isFinite(v) && v > 0).slice(0, 12);
const parseBRL = (value: string) => { const normalized = value.replace(/\s/g, "").replace(/R\$?/gi, "").replace(/\./g, "").replace(",", "."); const parsed = Number(normalized); return Number.isFinite(parsed) ? parsed : 0; };

export default function Home() {
  // The useAuth hook provides authentication state.
  // To implement login/logout, call logout(), or start login from an event
  // handler: onClick={() => startLogin()} (imported from "@/const"). Never call
  // startLogin() during render (no href={startLogin()}) — it mints a one-time
  // nonce cookie and must run only at the moment of navigation.
  const { user, loading, error, isAuthenticated, logout } = useAuth();
  const uploadFile = trpc.files.upload.useMutation();
  const sharedFlow = trpc.cashFlow.list.useQuery(undefined, { refetchInterval: 15_000 });
  const replaceSharedImport = trpc.cashFlow.replaceImport.useMutation();
  const confirmSharedPurchase = trpc.cashFlow.confirmPurchases.useMutation();

  const [tab, setTab] = useState<"fluxo" | "importar" | "metas" | "dashboard">("fluxo");
  const [entries, setEntries] = useState<Entry[]>([]);
  const [today, setToday] = useState(iso(new Date()));
  const [purchaseInput, setPurchaseInput] = useState("48.000,00");
  const [termsInput, setTermsInput] = useState("30, 60, 90");
  const [simulationMode, setSimulationMode] = useState<"terms" | "dates">("terms");
  const [paymentDatesInput, setPaymentDatesInput] = useState("");
  const [simulated, setSimulated] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);
  const [selectedTerms, setSelectedTerms] = useState<number[]>([]);
  const [showAdd, setShowAdd] = useState(false);
  const [newEntry, setNewEntry] = useState({ date: iso(new Date()), debit: "" });
  const [importSummary, setImportSummary] = useState<{ count: number; start: string; end: string; total: number } | null>(null);
  const [mobileMenu, setMobileMenu] = useState(false);
  const [now, setNow] = useState(Date.now());
  const legacyEntries = useMemo(loadEntries, []);
  const attemptedLegacyMigration = useRef(false);
  const terms = parseTerms(termsInput);
  const paymentDates = parsePaymentDates(paymentDatesInput);
  useEffect(() => { if (sharedFlow.data) setEntries(sharedFlow.data.map(entry => ({ id: String(entry.id), date: entry.date, debit: entry.debitCents / 100, source: entry.source, createdAt: entry.createdAt.getTime() }))); }, [sharedFlow.data]);
  useEffect(() => { if (!sharedFlow.isSuccess || attemptedLegacyMigration.current) return; attemptedLegacyMigration.current = true; if (sharedFlow.data.length || !legacyEntries.length) return; const imported = legacyEntries.filter(entry => entry.source === "imported"); const temporary = legacyEntries.filter(entry => entry.source === "manual" && isTemporaryEntryActive(entry, Date.now())); if (imported.length) replaceSharedImport.mutate({ entries: imported.map(entry => ({ date: entry.date, debitCents: Math.round(entry.debit * 100) })) }); if (temporary.length) confirmSharedPurchase.mutate({ entries: temporary.map(entry => ({ date: entry.date, debitCents: Math.round(entry.debit * 100) })) }); if (imported.length || temporary.length) { toast.success("Fluxo local migrado para a base compartilhada."); sharedFlow.refetch(); } }, [sharedFlow.isSuccess, sharedFlow.data, legacyEntries, replaceSharedImport, confirmSharedPurchase, sharedFlow]);
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 60000); return () => window.clearInterval(timer); }, []);
  const activeEntries = entries;
  const grouped = useMemo(() => { const groups = new Map<string, number>(); activeEntries.forEach((e) => groups.set(e.date, (groups.get(e.date) || 0) + Number(e.debit || 0))); return Array.from(groups.entries()).sort(([a], [b]) => a.localeCompare(b)).map(([date, debit]) => { const target = getPurchaseLimitForDate(date); return { date, debit, limit: target.limit, exceeded: debit > target.limit, critical: criticalLabel(date), weekday: target.weekday, isCritical: target.isCritical }; }); }, [activeEntries]);
  const total = grouped.reduce((s, d) => s + d.debit, 0);
  const dueToday = grouped.find((d) => d.date === today);
  const criticalRows = grouped.filter((d) => d.critical);
  const purchase = parseBRL(purchaseInput);
  const dueDates = useMemo(() => { const parsed = simulationMode === "dates" ? paymentDates.map((item) => ({ date: item.date, term: calculateDaysFromReference(today, item.date) })) : (terms.length ? terms : [30]).map((term) => { const d = new Date(`${today}T12:00:00`); d.setDate(d.getDate() + term); return { term, date: iso(d) }; }); const installment = parsed.length ? purchase / parsed.length : 0; return parsed.map(({ term, date }) => { const existing = grouped.find((row) => row.date === date)?.debit || 0; const target = getPurchaseLimitForDate(date); const canBuy = canPurchaseOnDate(date, existing, installment); return { term, date, existing, installment, limit: target.limit, weekday: target.weekday, isCritical: target.isCritical, canBuy }; }); }, [simulationMode, paymentDatesInput, terms, purchase, purchaseInput, today, grouped]);
  const addDebit = () => { const value = parseBRL(newEntry.debit); if (!newEntry.date || !value || value <= 0) return toast.error("Informe uma data e um débito válido."); confirmSharedPurchase.mutate({ entries: [{ date: newEntry.date, debitCents: Math.round(value * 100) }] }, { onSuccess: (rows) => { setEntries(rows.map(entry => ({ id: String(entry.id), date: entry.date, debit: entry.debitCents / 100, source: entry.source, createdAt: entry.createdAt.getTime() }))); setNewEntry({ date: today, debit: "" }); setShowAdd(false); toast.success("Registro compartilhado por 7 dias."); }, onError: () => toast.error("Não foi possível salvar o registro compartilhado.") }); };
  const confirmPurchase = () => { const selected = dueDates.filter((scenario) => selectedTerms.includes(scenario.term)); if (!selected.length) return toast.error("Selecione pelo menos um prazo para confirmar a compra."); confirmSharedPurchase.mutate({ entries: selected.map(scenario => ({ date: scenario.date, debitCents: Math.round(scenario.installment * 100) })) }, { onSuccess: (rows) => { setEntries(rows.map(entry => ({ id: String(entry.id), date: entry.date, debit: entry.debitCents / 100, source: entry.source, createdAt: entry.createdAt.getTime() }))); setShowConfirm(false); setSelectedTerms([]); toast.success(`${selected.length} parcela(s) confirmada(s) e compartilhadas. Todas as máquinas verão o fluxo atualizado.`); }, onError: () => toast.error("Não foi possível confirmar a compra compartilhada.") }); };
  
  const downloadTemplate = () => { const sheet = XLSX.utils.aoa_to_sheet([["Data de Operação", "Crédito", "Débito", "Saldo"], [today, 0, 0, 0]]); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, sheet, "Fluxo de Caixa"); XLSX.writeFile(wb, "modelo-fluxo-de-caixa.xlsx"); };
  const importFile = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const arrayBuffer = reader.result as ArrayBuffer; const wb = XLSX.read(arrayBuffer, { type: "array", cellDates: true }); const ws = wb.Sheets[wb.SheetNames[0]]; const rows = XLSX.utils.sheet_to_json<any[]>(ws, { header: 1, raw: true, defval: "" }); const headers = (rows[0] || []).map((h: any) => String(h).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")); const dateIndex = Math.max(0, headers.findIndex((h) => h.includes("data"))); const debitIndex = headers.findIndex((h) => h.includes("debito")); if (debitIndex < 0) throw new Error("Coluna Débito não encontrada"); const parseDate = (v: any) => v instanceof Date ? iso(v) : /^\d{4}-\d{2}-\d{2}$/.test(String(v)) ? String(v) : ""; const imported = rows.slice(1).map((r) => ({ date: parseDate(r[dateIndex]), debit: typeof r[debitIndex] === "number" ? r[debitIndex] : parseBRL(String(r[debitIndex] || "")) })).filter((e) => e.date && e.debit > 0); if (!imported.length) throw new Error("Nenhum débito válido encontrado"); if (isAuthenticated) { const bytes = new Uint8Array(arrayBuffer); let binary = ""; const chunkSize = 0x8000; for (let i = 0; i < bytes.length; i += chunkSize) binary += String.fromCharCode(...Array.from(bytes.subarray(i, i + chunkSize))); uploadFile.mutate({ fileName: file.name, mimeType: file.type || "application/octet-stream", byteSize: bytes.byteLength, base64: btoa(binary) }, { onError: () => toast.error("O fluxo foi atualizado, mas não foi possível arquivar a planilha.") }); } replaceSharedImport.mutate({ entries: imported.map(entry => ({ date: entry.date, debitCents: Math.round(entry.debit * 100) })) }, { onSuccess: (shared) => { setEntries(shared.map(entry => ({ id: String(entry.id), date: entry.date, debit: entry.debitCents / 100, source: entry.source, createdAt: entry.createdAt.getTime() }))); const dates = imported.map((entry) => entry.date).sort(); setImportSummary({ count: imported.length, start: dates[0], end: dates[dates.length - 1], total: imported.reduce((sum, entry) => sum + entry.debit, 0) }); toast.success(`${imported.length} lançamentos importados e compartilhados. A planilha agora é a fonte central do fluxo.`); }, onError: () => toast.error("Não foi possível atualizar o fluxo compartilhado.") }); } catch { toast.error("Não foi possível processar a planilha. Confira a coluna Débito."); } }; reader.readAsArrayBuffer(file); };
  return (
    <div className="simple-app">
      <header className="simple-header"><div className="brand"><div className="brand-mark">FC</div><div><strong>Fluxo de Caixa</strong><span>Contas a pagar</span></div></div><button className="mobile-menu" onClick={() => setMobileMenu(!mobileMenu)}><Menu size={20}/></button><nav className={mobileMenu ? "open" : ""}><button className={tab === "fluxo" ? "active" : ""} onClick={() => { setTab("fluxo"); setMobileMenu(false); }}>Fluxo de Caixa</button><button className={tab === "importar" ? "active" : ""} onClick={() => { setTab("importar"); setMobileMenu(false); }}>Importar Planilha</button><button className={tab === "metas" ? "active" : ""} onClick={() => { setTab("metas"); setMobileMenu(false); }}>Cadastro de Metas</button><button className={tab === "dashboard" ? "active" : ""} onClick={() => { setTab("dashboard"); setMobileMenu(false); }}>Dashboard de Compras</button></nav></header>
      <main className="simple-main">{tab === "fluxo" ? <>
        <div className="page-heading page-heading-compact"><div><p className="eyebrow">Contas a pagar</p><h1>Fluxo de Caixa</h1><p className="subheading">Simule compras futuras com os débitos importados.</p></div></div>
        <div className={simulated ? "sim-layout has-simulation" : "sim-layout"}>
          <aside className="card simulator simulator-large"><div className="card-heading"><div><h2>Simulador de compra</h2><p>Escolha prazos em dias ou informe diretamente as datas de pagamento. O valor será dividido entre as parcelas.</p></div><span className="sim-badge">SIMULAR</span></div><div className="form-stack"><label>Data de hoje<input type="date" value={today} onChange={(e) => setToday(e.target.value)}/></label><label>Valor total da compra<input type="text" inputMode="decimal" value={purchaseInput} onChange={(e) => setPurchaseInput(e.target.value)} onBlur={() => { const value = parseBRL(purchaseInput); setPurchaseInput(value ? value.toLocaleString("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : ""); }} placeholder="40.000,00"/></label><div className="simulation-mode"><span>Insira o prazo da compra em dias ou a data prevista do pagamento</span><div className="mode-options"><label><input type="radio" name="simulation-mode" checked={simulationMode === "terms"} onChange={() => setSimulationMode("terms")}/> Prazo em dias</label><label><input type="radio" name="simulation-mode" checked={simulationMode === "dates"} onChange={() => setSimulationMode("dates")}/> Data de pagamento</label></div></div>{simulationMode === "terms" ? <label>Prazo da compra em dias<input type="text" value={termsInput} onChange={(e) => setTermsInput(e.target.value)} placeholder="30, 60, 90"/><small className="field-hint">Exemplo: 30, 60, 90 divide o valor em 3 parcelas.</small></label> : <label>Datas previstas de pagamento<input type="text" value={paymentDatesInput} onChange={(e) => setPaymentDatesInput(e.target.value)} placeholder="11/09/2026, 11/10/2026, 11/11/2026"/><small className="field-hint">Informe uma ou mais datas separadas por vírgula. O valor será dividido igualmente.</small></label>}</div><button className="btn btn-primary full" onClick={() => { if (simulationMode === "dates" && !paymentDates.length) return toast.error("Informe pelo menos uma data no formato DD/MM/AAAA."); if (simulationMode === "terms" && !terms.length) return toast.error("Informe pelo menos um prazo em dias."); setSimulated(true); toast.success("Cenários de compra simulados."); }}>Simular compra</button></aside>
          {simulated && <section className="card simulation-panel"><div className="card-heading"><div><h2>Simulação da compra</h2><p>Confira cada parcela, impacto e meta calculada para a data prevista.</p></div></div><div className="scenario-list">{dueDates.map((scenario) => <div className={"scenario " + (scenario.canBuy ? "scenario-ok" : "scenario-risk")} key={scenario.term}><div className="scenario-title"><strong>{scenario.canBuy ? "PODE COMPRAR" : "NÃO PODE COMPRAR"}</strong><span>{simulationMode === "dates" ? "Data informada" : `${scenario.term} dias`}</span></div><div className="scenario-grid"><div><span>Data prevista</span><strong>{dateBR(scenario.date)}</strong></div><div><span>Prazo</span><strong>Hoje + {scenario.term} dias</strong></div><div><span>Dia da semana</span><strong>{scenario.weekday}</strong></div><div><span>Valor já existente</span><strong>{money(scenario.existing)}</strong></div><div><span>Valor da compra</span><strong>{money(scenario.installment)}</strong></div><div><span>{scenario.isCritical ? "Limite crítico" : "Meta do dia"}</span><strong>{money(scenario.limit)}</strong></div></div><p>{scenario.canBuy ? "Débitos existentes + parcela ficam dentro do limite." : "Débitos existentes + parcela ultrapassam o limite."}</p></div>)}</div><button className="btn btn-dark full confirm-purchase-btn" onClick={() => { setSelectedTerms(dueDates.map((scenario) => scenario.term)); setShowConfirm(true); }}>Confirmar compra nessas parcelas</button></section>}
        </div>
        <section className="card critical-card critical-below"><div className="card-heading"><div><h2>Dias críticos e datas de pagamento</h2><p>À esquerda, os eventos críticos; à direita, as datas, dias da semana e metas aplicadas.</p></div><AlertTriangle size={20}/></div><div className="critical-list">{criticalRows.map((d) => <div className={"critical-item " + (d.exceeded ? "critical-risk" : "")} key={d.date}><div className="critical-event"><strong>{d.critical}</strong><span>Dia crítico de pagamento</span></div><div className="critical-date"><strong>{dayMonthBR(d.date)}</strong><span>{d.weekday} · limite de {money(d.limit)}</span></div><div className="critical-amount"><b className={d.exceeded ? "red-text" : "green-text"}>{money(d.debit)}</b><small>{d.exceeded ? "limite ultrapassado" : `${money(d.limit - d.debit)} livres`}</small></div></div>)}{!criticalRows.length && <div className="empty">Nenhuma data crítica carregada.</div>}</div></section>
        <section className="card timeline-card"><div className="card-heading"><div><h2>Débitos por dia</h2><p>Todos os débitos importados, organizados por data e comparados com a meta do dia.</p></div><WalletCards size={20}/></div><div className="timeline-list">{grouped.map((d) => <div className="timeline-row" key={d.date}><div className="timeline-label"><strong>{dateBR(d.date)}</strong><span>{d.critical || d.weekday}</span></div><div className="timeline-track"><div className={"timeline-fill " + (d.exceeded ? "fill-risk" : "")} style={{ width: String(Math.min(100, d.debit / d.limit * 100)) + "%" }}/></div><div className="timeline-value"><strong className={d.exceeded ? "red-text" : "green-text"}>{money(d.debit)}</strong><span>{d.exceeded ? "Limite ultrapassado" : `${money(d.limit - d.debit)} livres`}</span></div></div>)}{!grouped.length && <div className="empty">Nenhum débito importado. Acesse “Importar Planilha” para começar.</div>}</div></section>
      </> : tab === "importar" ? <ImportTab onFile={importFile} onDownload={downloadTemplate} summary={importSummary}/> : tab === "metas" ? <GoalsTab/> : <PurchasesDashboardTab/>}</main>
      {showConfirm && <div className="modal-backdrop"><div className="modal-light confirmation-modal"><div className="modal-title"><div><p className="eyebrow">Reprocessar fluxo</p><h2>Confirmar compra</h2></div><button className="icon-btn" onClick={() => setShowConfirm(false)}><X size={18}/></button></div><p className="modal-description">Selecione as parcelas que foram confirmadas. As parcelas escolhidas entram no fluxo nas datas previstas e ficam temporárias por 7 dias.</p><div className="confirmation-terms">{dueDates.map((scenario) => <label className="confirmation-term" key={scenario.term}><input type="checkbox" checked={selectedTerms.includes(scenario.term)} onChange={(e) => setSelectedTerms((current) => e.target.checked ? [...current, scenario.term] : current.filter((term) => term !== scenario.term))}/><span><strong>{simulationMode === "dates" ? dateBR(scenario.date) : `${scenario.term} dias`}</strong><small>{dateBR(scenario.date)} · {money(scenario.installment)}</small></span></label>)}</div><div className="modal-actions"><button className="btn btn-light" onClick={() => setShowConfirm(false)}>Cancelar</button><button className="btn btn-dark" onClick={confirmPurchase}>Confirmar e atualizar fluxo</button></div></div></div>}
      {showAdd && <div className="modal-backdrop"><div className="modal-light"><div className="modal-title"><div><p className="eyebrow">Registro temporário</p><h2>Adicionar dia e valor compra</h2></div><button className="icon-btn" onClick={() => setShowAdd(false)}><X size={18}/></button></div><p className="modal-description">Este valor ajuda os compradores durante os próximos 7 dias e depois deixa de afetar o fluxo. A planilha importada continua sendo a fonte principal.</p><div className="form-stack"><label>Data de vencimento<input type="date" value={newEntry.date} onChange={(e) => setNewEntry({ ...newEntry, date: e.target.value })}/></label><label>Valor do débito<input type="number" min="0" value={newEntry.debit} onChange={(e) => setNewEntry({ ...newEntry, debit: e.target.value })}/></label></div><div className="modal-actions"><button className="btn btn-light" onClick={() => setShowAdd(false)}>Cancelar</button><button className="btn btn-dark" onClick={addDebit}>Salvar registro por 7 dias</button></div></div></div>}
    </div>
  );
}
function ImportTab({ onFile, onDownload, summary }: { onFile: (file?: File) => void; onDownload: () => void; summary: { count: number; start: string; end: string; total: number } | null }) { return <section className="import-page" aria-label="Importar planilha de débitos"><div className="page-heading"><div><p className="eyebrow">Atualização diária</p><h1>Importar Planilha</h1><p className="subheading">Envie o arquivo de contas a pagar. O sistema usa somente Data de Operação e Débito.</p></div></div><div className="import-grid"><label className="dropzone"><input type="file" accept=".xlsx,.csv" onChange={(e) => onFile(e.target.files?.[0])}/><Upload size={30}/><strong>Selecionar arquivo Excel</strong><span>.xlsx ou .csv</span></label><div className="card import-help"><FileSpreadsheet size={24}/><h2>Modelo correto</h2><p>O arquivo deve conter exatamente estas quatro colunas:</p><div className="columns"><span>1. Data de Operação</span><span>2. Crédito</span><span>3. Débito</span><span>4. Saldo</span></div><p className="muted">Durante o processamento, Crédito e Saldo são ignorados. Apenas Débito monta o fluxo.</p><button className="btn btn-dark full" onClick={onDownload}><Download size={16}/> Baixar modelo .xlsx</button></div></div>{summary && <div className="import-summary"><CheckCircle2 size={22}/><div><strong>Importação concluída</strong><span>{summary.count} lançamentos lidos · período de {dateBR(summary.start)} a {dateBR(summary.end)} · total de débitos: {money(summary.total)}</span></div></div>}</section>; }
